CREATE TABLE IF NOT EXISTS `nd_vehicles` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`owner` INT(11) DEFAULT NULL,
	`plate` VARCHAR(20) DEFAULT NULL,
	`properties` LONGTEXT DEFAULT '{}',
	`makeName` VARCHAR(50) DEFAULT NULL,
	`modelName` VARCHAR(50) DEFAULT NULL,
	`className` VARCHAR(50) DEFAULT NULL,
	`stolen` INT(11) DEFAULT 0,
	PRIMARY KEY (`id`) USING BTREE
);
